Refactor branch and commit validation logic

diff --git a/bin/git-updatepr b/bin/git-updatepr
--- a/bin/git-updatepr
+++ b/bin/git-updatepr
@@ -42,20 +42,17 @@ fi
 if git show-ref --quiet --verify "refs/heads/$sha_or_branch_to_update"; then
   branch_name="$sha_or_branch_to_update"
   commit_to_update=$(git rev-parse --verify "$branch_name" 2>/dev/null)
-else
+elif ! git cat-file -e "$sha_or_branch_to_update" 2>/dev/null; then
   commit_to_update="$sha_or_branch_to_update"
   branch_name="$(git pilebranchname "$commit_to_update")"
-fi
 
-# Check if we got a valid SHA
-if ! git cat-file -e "$commit_to_update" 2>/dev/null; then
-  echo "error: invalid commit sha or branch name: '$1'" >&2
-  exit 1
-fi
-
-# Check if we got a valid branch
-if ! git show-ref --quiet "$branch_name"; then
-  echo "error: branch '$branch_name' doesn't exist" >&2
+  # Check if we got a valid branch
+  if ! git show-ref --quiet "$branch_name"; then
+    echo "error: branch '$branch_name' doesn't exist" >&2
+    exit 1
+  fi
+else
+  echo "error: invalid commit sha or branch name: '$sha_or_branch_to_update'" >&2
   exit 1
 fi
 
