Remove ghb support
Makes it easier for me to test that things work for everyone else too

diff --git a/bin/git-submitpr b/bin/git-submitpr
--- a/bin/git-submitpr
+++ b/bin/git-submitpr
@@ -97,81 +97,68 @@ cleanup_remote_branch() {
 
 error_file=$(mktemp)
 if git -C "$worktree_dir" remote get-url mine 2>/dev/null && git -C "$worktree_dir" push --quiet --set-upstream mine "$branch_name"; then
-  if command -v gh >/dev/null; then
-    # TODO: does gh not support -C either?
-    pushd "$worktree_dir" >/dev/null
-    # TODO: pass --repo with value from origin?
-    gh pr create --web
-    popd >/dev/null
-  else
-    # TODO: Example URL for upstream fork PRs https://github.com/apple/swift/compare/release/5.6...keith:ks/fix-invalid-warning-for-enum-cases-named-self-41520?expand=1
-    git -C "$worktree_dir" open --remote mine "pull/new/$branch_name"
-  fi
+  # TODO: does gh not support -C either?
+  pushd "$worktree_dir" >/dev/null
+  # TODO: pass --repo with value from origin?
+  gh pr create --web
+  popd >/dev/null
 elif git -C "$worktree_dir" push --quiet --set-upstream origin "$branch_name" 2> "$error_file"; then
-  if command -v ghb > /dev/null; then
-    # TODO maybe ghb should support -C ?
-    pushd "$worktree_dir" >/dev/null
-    if ! ghb pr --no-edit "$remote_branch_name" "$@"; then
-      cleanup_remote_branch
-    fi
-
-    popd >/dev/null
-  elif command -v gh > /dev/null; then
-    # TODO: does gh not support -C either?
-    pushd "$worktree_dir" >/dev/null
-    body_args=(--fill)
-    if [[ -n ${GIT_PILE_USE_PR_TEMPLATE:-} && -f .github/pull_request_template.md ]]; then
-      subject=$(git -C "$worktree_dir" show -s --format=%s HEAD)
-      body=$(git -C "$worktree_dir" show -s --format=%b HEAD)
-      if [[ -n "$body" ]]; then
-        body=$(printf '%s\n\n%s' "$body" "$(cat .github/pull_request_template.md)")
-      else
-        body="$(cat .github/pull_request_template.md)"
-      fi
-      body_args=(--title "$subject" --body "$body")
-    fi
-
-    pr_args=()
-    merge_arg=""
-    for arg in "$@"
-    do
-      case "$arg" in
-        --merge-squash)
-          merge_arg="--squash"
-          shift
-          ;;
-        --merge-rebase)
-          merge_arg="--rebase"
-          shift
-          ;;
-        --merge)
-          merge_arg="--merge"
-          shift
-          ;;
-        *)
-          pr_args+=("$arg")
-          shift
-          ;;
-      esac
-    done
-
-    if url=$(gh pr create "${body_args[@]}" --base "$remote_branch_name" "${pr_args[@]:---}" | grep github.com); then
-      native_open "$url"
-
-      # TODO: should I set subject and body?
-      if [[ -n "$merge_arg" ]] && ! gh pr merge "$url" --auto "$merge_arg"; then
-        echo "warning: failed to auto-merge PR with $merge_arg" >&2
-        exit 1
-      fi
-    else
-      cleanup_remote_branch
-    fi
-
-    popd >/dev/null
-  else
-    echo "error: no tool to create a PR, install gh: https://cli.github.com/" >&2
+  if ! command -v gh > /dev/null; then
+    echo "error: missing gh, install here: https://cli.github.com" >&2
     exit 1
   fi
+
+  # TODO: does gh not support -C either?
+  pushd "$worktree_dir" >/dev/null
+  body_args=(--fill)
+  if [[ -n ${GIT_PILE_USE_PR_TEMPLATE:-} && -f .github/pull_request_template.md ]]; then
+    subject=$(git -C "$worktree_dir" show -s --format=%s HEAD)
+    body=$(git -C "$worktree_dir" show -s --format=%b HEAD)
+    if [[ -n "$body" ]]; then
+      body=$(printf '%s\n\n%s' "$body" "$(cat .github/pull_request_template.md)")
+    else
+      body="$(cat .github/pull_request_template.md)"
+    fi
+    body_args=(--title "$subject" --body "$body")
+  fi
+
+  pr_args=()
+  merge_arg=""
+  for arg in "$@"
+  do
+    case "$arg" in
+      --merge-squash)
+        merge_arg="--squash"
+        shift
+        ;;
+      --merge-rebase)
+        merge_arg="--rebase"
+        shift
+        ;;
+      --merge)
+        merge_arg="--merge"
+        shift
+        ;;
+      *)
+        pr_args+=("$arg")
+        shift
+        ;;
+    esac
+  done
+
+  if url=$(gh pr create "${body_args[@]}" --base "$remote_branch_name" "${pr_args[@]:---}" | grep github.com); then
+    native_open "$url"
+
+    # TODO: should I set subject and body?
+    if [[ -n "$merge_arg" ]] && ! gh pr merge "$url" --auto "$merge_arg"; then
+      echo "warning: failed to auto-merge PR with $merge_arg" >&2
+      exit 1
+    fi
+  else
+    cleanup_remote_branch
+  fi
+
+  popd >/dev/null
 else
   echo "error: failed to create remote branch: $(cat "$error_file")" >&2
   _detach_branch
