Fix failed cherry pick bad state
I'm not sure about skipping vs aborting here, maybe there's a case where
cherry picking something that was also pulled from upstream is ok and
we'd like it to continue to squash on the main branch.

diff --git a/bin/git-submitpr b/bin/git-submitpr
--- a/bin/git-submitpr
+++ b/bin/git-submitpr
@@ -47,8 +47,13 @@ trap _detach_branch EXIT
 
 if ! git -C "$worktree_dir" cherry-pick "$commit" >/dev/null; then
   if git -C "$worktree_dir" mergetool; then
-    # TODO: if you mess up the cherry pick and leave with no changes this doesn't handle that, in that case we need skip or abort
-    git -C "$worktree_dir" -c core.editor=true cherry-pick --continue
+    if ! git -C "$worktree_dir" -c core.editor=true cherry-pick --continue; then
+      git -C "$worktree_dir" cherry-pick --abort || true
+      _detach_branch
+      git branch -D "$branch_name"
+      echo "error: cherry picking failed, maybe there wasn't a commit to cherry pick?" >&2
+      exit 1
+    fi
   else
     git -C "$worktree_dir" cherry-pick --abort
     _detach_branch
