Quiet some output

diff --git a/bin/git-submitpr b/bin/git-submitpr
--- a/bin/git-submitpr
+++ b/bin/git-submitpr
@@ -33,7 +33,7 @@ if [[ ! -d "$worktree_dir" ]]; then
   git worktree add -f "$worktree_dir" "$branch_name"
 else
   # TODO: I've had the repo be in a bad state and maybe we need a cherry pick abort here, or on the cleanup instead
-  if ! git -C "$worktree_dir" switch "$branch_name"; then
+  if ! git -C "$worktree_dir" switch --quiet "$branch_name"; then
     git branch -D "$branch_name"
     exit 1
   fi
@@ -45,7 +45,7 @@ _detach_branch() {
 
 trap _detach_branch EXIT
 
-if ! git -C "$worktree_dir" cherry-pick "$commit"; then
+if ! git -C "$worktree_dir" cherry-pick "$commit" >/dev/null; then
   if git -C "$worktree_dir" mergetool; then
     # TODO: if you mess up the cherry pick and leave with no changes this doesn't handle that, in that case we need skip or abort
     git -C "$worktree_dir" -c core.editor=true cherry-pick --continue
@@ -57,6 +57,7 @@ if ! git -C "$worktree_dir" cherry-pick "$commit"; then
   fi
 fi
 
+error_file=$(mktemp)
 if git -C "$worktree_dir" remote get-url mine 2>/dev/null && git -C "$worktree_dir" push --quiet --set-upstream mine "$branch_name"; then
   if command -v gh >/dev/null; then
     gh pr create --web
@@ -64,7 +65,7 @@ if git -C "$worktree_dir" remote get-url mine 2>/dev/null && git -C "$worktree_d
     # TODO: Example URL for upstream fork PRs https://github.com/apple/swift/compare/release/5.6...keith:ks/fix-invalid-warning-for-enum-cases-named-self-41520?expand=1
     git -C "$worktree_dir" open --remote mine "pull/new/$branch_name"
   fi
-elif git -C "$worktree_dir" push --quiet --set-upstream origin "$branch_name"; then
+elif git -C "$worktree_dir" push --quiet --set-upstream origin "$branch_name" 2> "$error_file"; then
   if command -v ghb > /dev/null; then
     # TODO maybe ghb should support -C ?
     pushd "$worktree_dir" >/dev/null
@@ -81,7 +82,7 @@ elif git -C "$worktree_dir" push --quiet --set-upstream origin "$branch_name"; t
     exit 1
   fi
 else
-  echo "error: failed to create remote branch" >&2
+  echo "error: failed to create remote branch: $(cat "$error_file")" >&2
   _detach_branch
   git branch -D "$branch_name"
 fi
