Move gh cli check

diff --git a/bin/git-submitpr b/bin/git-submitpr
--- a/bin/git-submitpr
+++ b/bin/git-submitpr
@@ -6,6 +6,11 @@ if [[ -n "${GIT_PILE_VERBOSE:-}" ]]; then
   set -x
 fi
 
+if ! command -v gh > /dev/null; then
+  echo "error: missing gh, install here: https://cli.github.com" >&2
+  exit 1
+fi
+
 commit_arg=HEAD
 if [[ $# -gt 0 ]]; then
   if [[ $1 != --* ]]; then
@@ -103,11 +108,6 @@ if git -C "$worktree_dir" remote get-url mine 2>/dev/null && git -C "$worktree_d
   gh pr create --web
   popd >/dev/null
 elif git -C "$worktree_dir" push --quiet --set-upstream origin "$branch_name" 2> "$error_file"; then
-  if ! command -v gh > /dev/null; then
-    echo "error: missing gh, install here: https://cli.github.com" >&2
-    exit 1
-  fi
-
   # TODO: does gh not support -C either?
   pushd "$worktree_dir" >/dev/null
   body_args=(--fill)
