Add support for gh

diff --git a/bin/git-submitpr b/bin/git-submitpr
--- a/bin/git-submitpr
+++ b/bin/git-submitpr
@@ -58,13 +58,28 @@ if ! git -C "$worktree_dir" cherry-pick "$commit"; then
 fi
 
 if git -C "$worktree_dir" remote get-url mine 2>/dev/null && git -C "$worktree_dir" push --quiet --set-upstream mine "$branch_name"; then
-  # TODO: Example URL for upstream fork PRs https://github.com/apple/swift/compare/release/5.6...keith:ks/fix-invalid-warning-for-enum-cases-named-self-41520?expand=1
-  git -C "$worktree_dir" open --remote mine "pull/new/$branch_name"
+  if command -v gh >/dev/null; then
+    gh pr create --web
+  else
+    # TODO: Example URL for upstream fork PRs https://github.com/apple/swift/compare/release/5.6...keith:ks/fix-invalid-warning-for-enum-cases-named-self-41520?expand=1
+    git -C "$worktree_dir" open --remote mine "pull/new/$branch_name"
+  fi
 elif git -C "$worktree_dir" push --quiet --set-upstream origin "$branch_name"; then
-  # TODO maybe ghb should support -C ?
-  pushd "$worktree_dir" >/dev/null
-  ghb pr --no-edit --draft "$remote_branch_name" "$@"
-  popd
+  if command -v ghb > /dev/null; then
+    # TODO maybe ghb should support -C ?
+    pushd "$worktree_dir" >/dev/null
+    ghb pr --no-edit --draft "$remote_branch_name" "$@"
+    popd >/dev/null
+  elif command -v gh > /dev/null; then
+    # TODO: does gh not support -C either?
+    pushd "$worktree_dir" >/dev/null
+    url=$(gh pr create --draft --fill --base "$remote_branch_name" "$@" | grep github.com)
+    open "$url"
+    popd >/dev/null
+  else
+    echo "error: no tool to create a PR, install gh: https://cli.github.com/" >&2
+    exit 1
+  fi
 else
   echo "error: failed to create remote branch" >&2
   _detach_branch
