Automatically derive GitLab merge URL

diff --git a/bin/git-submitpr b/bin/git-submitpr
--- a/bin/git-submitpr
+++ b/bin/git-submitpr
@@ -12,9 +12,19 @@ gitlab_mode_enabled=$(git config --default false --type=bool pile.gitlabModeEnab
 gitlab_url=$(git config --default '' pile.gitlabMergeRequestsURL)
 
 if [[ $gitlab_mode_enabled = true ]]; then
-  if [[ -z $gitlab_url ]]; then
-    echo "error: GitLab is enabled, but no URL is set, run 'git config pile.gitlabMergeRequestsURL \"https://gitlab.com/{group}/{project}/-/merge_requests/new\"' to configure it" >&2
-    exit 1
+  if [[ -z "$gitlab_url" ]]; then
+    origin_url=$(git remote get-url origin | sed 's/\.git$//')
+    ssh_pattern="^git@(git\.)?([^:]+):(.+)$"
+    https_pattern="^https:\/\/(.+)$"
+    if [[ $origin_url =~ $ssh_pattern ]]; then
+      gitlab_url="https://${BASH_REMATCH[2]}/${BASH_REMATCH[3]}/-/merge_requests/new"
+    elif [[ $origin_url =~ $https_pattern ]]; then
+      gitlab_url="https://${BASH_REMATCH[1]}/-/merge_requests/new"
+    else
+      echo "error: Cannot derive GitLab merge request URL from origin"
+      echo "error: GitLab is enabled, but no URL is set, run 'git config pile.gitlabMergeRequestsURL \"https://gitlab.com/{group}/{project}/-/merge_requests/new\"' to configure it" >&2
+      exit 1
+    fi
   fi
 else
   if ! command -v gh > /dev/null; then
