Add some error handling to pilebranchname (#68)
Can't remember why this was needed

diff --git a/bin/git-pilebranchname b/bin/git-pilebranchname
--- a/bin/git-pilebranchname
+++ b/bin/git-pilebranchname
@@ -3,6 +3,16 @@
 set -euo pipefail
 
 readonly ref=$1
+if [[ "$ref" == -* ]]; then
+  echo "error: invalid ref starts with dash: $ref" >&2
+  exit 1
+fi
 
-branch_name="${GIT_PILE_PREFIX:-}$(git show --no-patch --no-show-signature --format=%f "$ref" | tr '[:upper:]' '[:lower:]' | sed -e 's/^\.*//' -e 's/\.lock$/-lock/')"
+branch=$(git show --no-patch --no-show-signature --format=%f "$ref")
+if [[ -z "$branch" ]]; then
+  echo "error: no branch found for ref: $ref" >&2
+  exit 1
+fi
+
+branch_name="${GIT_PILE_PREFIX:-}$(echo "$branch" | tr '[:upper:]' '[:lower:]' | sed -e 's/^\.*//' -e 's/\.lock$/-lock/')"
 echo "$branch_name"
